/*
 * Каталог скинов — единственный источник правды.
 * Отсюда живут витрина, реестр переключателя и (потом) магазин.
 *
 * ПРАВИЛО ИМЁН: никаких товарных знаков, марок и названий franchise.
 * Мы берём узнаваемую стилистику, а называем своим — как это делает Rockstar.
 * «Терминатор» нельзя, «Arnoldator» можно. Если название вызывает улыбку
 * узнавания и при этом не является чужим именем — оно годится.
 *
 * status:
 *   ready   — собран на реальных данных, лежит в skins/
 *   draft   — макет есть, к движку не подключён, лежит в concepts/
 *   planned — только описание в docs/ROADMAP.md
 *
 * price — цена в монетах. Пока магазин выключен, поле не используется,
 * но заполняется сразу, чтобы включение было настройкой, а не переделкой.
 */
window.SKIN_CATALOG = {

    groups: [
        { id: 'terminals',   title: 'Терминалы',        note: 'История вычислительной техники и строгий функционал' },
        { id: 'instruments', title: 'Приборы',          note: 'Механика, оптика, тактильность' },
        { id: 'games',       title: 'Игры',             note: 'Пиксель, чиптюн, аркадный замер' },
        { id: 'screen',      title: 'Экран',            note: 'Кино, сериалы, анимация' }
    ],

    skins: [
        // ── Терминалы ───────────────────────────────────────────────────────
        { id: 'base',      group: 'terminals',   status: 'ready',   price: 0,  file: '../index.html',
          name: 'Прибор',            note: 'Базовый тёмный. Всегда бесплатный' },
        { id: 'amber',     group: 'terminals',   status: 'draft',   price: 4,
          name: 'Янтарь',            note: 'Кинескоп, тёплое свечение, гул трансформатора' },
        { id: 'green',     group: 'terminals',   status: 'draft',   price: 4,
          name: 'Фосфор',            note: 'Зелёный военный пульт, треск телетайпа' },
        { id: 'cyan',      group: 'terminals',   status: 'draft',   price: 4,
          name: 'Циан',              note: 'Холодные вакуумные трубки, высокочастотный писк' },
        { id: 'mono',      group: 'terminals',   status: 'draft',   price: 4,
          name: 'Монохром',          note: 'Чернила по белому, щелчок мыши из восьмидесятых' },
        { id: 'stylus',    group: 'terminals',   status: 'planned', price: 6,
          name: 'Стилус 93',         note: 'Серый пластик, тусклый LCD, рукописный ввод' },
        { id: 'wheel',     group: 'terminals',   status: 'planned', price: 6,
          name: 'Колесо',            note: 'Чёрно-белый плеер, щелчок на каждый градус' },
        { id: 'eink',      group: 'terminals',   status: 'planned', price: 6,
          name: 'Читалка',           note: 'Электронная бумага, мерцание при обновлении, тишина' },
        { id: 'zen',       group: 'terminals',   status: 'planned', price: 8,
          name: 'Дзэн',              note: 'Пустота, солнце как единственный акцент, сиси-одоси' },

        // ── Приборы ─────────────────────────────────────────────────────────
        { id: 'braun',     group: 'instruments', status: 'ready',   price: 0,  file: 'braun.html',
          name: 'SN-01',             note: 'Кремовый корпус, светодиодная шкала, механический счётчик' },
        { id: 'lunar',     group: 'instruments', status: 'planned', price: 10,
          name: 'Лунный модуль',     note: 'Сегментные цифры, инженерные таблицы, треск эфира' },
        { id: 'orient',    group: 'instruments', status: 'planned', price: 8,
          name: 'Система ориентации',note: 'Молотковый металл, лампы накаливания, тумблеры' },
        { id: 'rangefinder',group:'instruments', status: 'planned', price: 10,
          name: 'Дальномер',         note: 'Латунь на гранях, кольцо диафрагмы, звук затвора' },
        { id: 'steampunk', group: 'instruments', status: 'planned', price: 8,
          name: 'Хронометр',         note: 'Викторианская латунь, открытые шестерёнки' },
        { id: 'nautical',  group: 'instruments', status: 'planned', price: 8,
          name: 'Штурманский',       note: 'Красное дерево, роза ветров, удар рынды' },
        { id: 'astrolabe', group: 'instruments', status: 'planned', price: 10,
          name: 'Астролябия',        note: 'Бронза, зодиакальные гравировки, камень о металл' },
        { id: 'alchemist', group: 'instruments', status: 'planned', price: 8,
          name: 'Алхимик',           note: 'Пергамент, латынь, царапающее перо' },
        { id: 'film',      group: 'instruments', status: 'planned', price: 8,
          name: 'Плёнка 400',        note: 'Жёлтая коробка, кожзам, шкалы экспонометра' },
        { id: 'instant',   group: 'instruments', status: 'planned', price: 8,
          name: 'Моменталка',        note: 'Белый пластик, снимок выезжает и проявляется' },
        { id: 'oscillator',group: 'instruments', status: 'planned', price: 10,
          name: 'Осциллятор',        note: 'Алюминий, крутилки, бас зависит от высоты солнца' },
        { id: 'weather',   group: 'instruments', status: 'planned', price: 6,
          name: 'Метеостанция',      note: 'Грубый пластик девяностых, UV-индекс' },
        { id: 'rover',     group: 'instruments', status: 'planned', price: 10,
          name: 'Марсоход',          note: 'Красная пыль на экране, MISSION DAY' },
        { id: 'skeleton',  group: 'instruments', status: 'planned', price: 10,
          name: 'Скелетон',          note: 'Открытый механизм с рубинами, тиканье' },
        { id: 'station',   group: 'instruments', status: 'planned', price: 6,
          name: 'Вокзальные часы',   note: 'Красная лопатка, пауза перед новым циклом' },
        { id: 'orbital',   group: 'instruments', status: 'planned', price: 10,
          name: 'Орбитальный',       note: 'Спектры и звёздные каталоги, гул гироскопов' },

        // ── Игры ────────────────────────────────────────────────────────────
        { id: 'invaders',  group: 'games',       status: 'draft',   price: 6,
          name: 'Захватчики',        note: 'Звёздное небо, спрайты, сдвоенный лазер' },
        { id: 'grinder',   group: 'games',       status: 'planned', price: 8,
          name: 'Мясорубка',         note: 'Ржавый металл, лицо героя, помповый дробовик' },
        { id: 'olive',     group: 'games',       status: 'planned', price: 6,
          name: 'Оливковый экран',   note: 'Пиксельная матрица, серая рамка, джингл запуска' },
        { id: 'shelter',   group: 'games',       status: 'planned', price: 8,
          name: 'Убежище',           note: 'Фосфорный монитор, царапины, счётчик Гейгера' },
        { id: 'dungeon',   group: 'games',       status: 'planned', price: 8,
          name: 'Подземелье',        note: 'Токсичный неон, готика, критический удар' },
        { id: 'hill',      group: 'games',       status: 'planned', price: 6,
          name: 'Зелёный холм',      note: 'Шахматная земля, кольца, звук сбора' },
        { id: 'bricks',    group: 'games',       status: 'planned', price: 4,
          name: 'Кирпичи',           note: 'Серый экран, падающие фигуры, схлопывание линии' },
        { id: 'plumber',   group: 'games',       status: 'planned', price: 6,
          name: 'Водопроводчик',     note: 'Кирпичные блоки, трубы, монета из блока' },
        { id: 'retrofuture',group:'games',       status: 'planned', price: 8,
          name: 'Ретрофутур',        note: 'Белый пластик пятидесятых, щелчок радиолампы' },
        { id: 'blocks',    group: 'games',       status: 'planned', price: 6,
          name: 'Блоки',             note: 'Квадратное солнце, хотбар, звук достижения' },
        { id: 'sandbox',   group: 'games',       status: 'planned', price: 6,
          name: 'Песочница',         note: 'Тёмный пиксель, инвентарь, взмах меча' },
        { id: 'corporate', group: 'games',       status: 'planned', price: 6,
          name: 'Корпорация',        note: 'Мультяшный плакат, голос диктора из пятидесятых' },
        { id: 'aperture',  group: 'games',       status: 'planned', price: 8,
          name: 'Лаборатория',       note: 'Стерильный пластик, оранжевый портал вокруг солнца' },
        { id: 'cube',      group: 'games',       status: 'planned', price: 6,
          name: 'Кубик-компаньон',   note: 'Серо-розовый металл с сердечками, нежный аккорд' },
        { id: 'dex',       group: 'games',       status: 'planned', price: 8,
          name: 'Солнцедекс',        note: 'Красный глянец, точечный экран, сканирование базы' },
        { id: 'runes',     group: 'games',       status: 'planned', price: 8,
          name: 'Древние руны',      note: 'Каменная плита, синий неон, капля в святилище' },
        { id: 'syndicate', group: 'games',       status: 'planned', price: 8,
          name: 'Синдикат',          note: 'Биомеханика, чужие символы, скрежет шлюзов' },

        // ── Экран ───────────────────────────────────────────────────────────
        { id: 'mischief',  group: 'screen',      status: 'planned', price: 8,
          name: 'Карта проказников', note: 'Пергамент, чернильные следы, взмах палочки' },
        { id: 'neon',      group: 'screen',      status: 'planned', price: 8,
          name: 'Неоновый Токио',    note: 'Голограммы, иероглифы, синтезатор' },
        { id: 'grid',      group: 'screen',      status: 'planned', price: 8,
          name: 'Сетка',             note: 'Векторный неон, разгон светового мотоцикла' },
        { id: 'rain',      group: 'screen',      status: 'planned', price: 8,
          name: 'Цифровой дождь',    note: 'Падающие символы собираются в азимут' },
        { id: 'esper',     group: 'screen',      status: 'planned', price: 10,
          name: 'Эспер',             note: 'Янтарный кинескоп, послойный анализ изображения' },
        { id: 'tug',       group: 'screen',      status: 'planned', price: 10,
          name: 'Буксир',            note: 'Белые панели, зелёные индикаторы, треск клавиатуры' },
        { id: 'arnoldator',group: 'screen',      status: 'planned', price: 10,
          name: 'Arnoldator',        note: 'Красный прицел на чёрном металле, сервоприводы' },
        { id: 'eye9000',   group: 'screen',      status: 'planned', price: 10,
          name: 'Око 9000',          note: 'Единственный красный объектив, пугающе спокойный голос' },
        { id: 'backforth', group: 'screen',      status: 'planned', price: 10,
          name: 'Вперёд в прошлое',  note: 'Сегментные индикаторы, разряд накопителя' },
        { id: 'itsunix',   group: 'screen',      status: 'planned', price: 8,
          name: 'Это же ЮНИКС',      note: 'Трёхмерная файловая система, крик ящера' },
        { id: 'imperial',  group: 'screen',      status: 'planned', price: 10,
          name: 'Имперский терминал',note: 'Чужой алфавит, чёрно-красные схемы, зуммер' },
        { id: 'iso',       group: 'screen',      status: 'planned', price: 8,
          name: 'Сетка 2.0',         note: 'Синий и оранжевый, энергетические кольца, басовый гул' },
        { id: 'sixth',     group: 'screen',      status: 'planned', price: 8,
          name: 'Шестой элемент',    note: 'Каменные блоки стихий, мистическое сияние' },
        { id: 'refinement',group: 'screen',      status: 'planned', price: 8,
          name: 'Отдел уточнения',   note: 'Тревожный корпоративный монитор, гул ламп' },
        { id: 'strange',   group: 'screen',      status: 'planned', price: 8,
          name: 'Очень дельные странности', note: 'Потёртая плёнка, гирлянды по краям, синт' },
        { id: 'bridge',    group: 'screen',      status: 'planned', price: 8,
          name: 'Мостик',            note: 'Изогнутые панели, оранжевый и фиолетовый' },
        { id: 'steamboat', group: 'screen',      status: 'planned', price: 6,
          name: 'Пароходик 1928',    note: 'Дёргающаяся плёнка, штриховка, гудок' },
        { id: 'mortricky', group: 'screen',      status: 'planned', price: 8,
          name: 'Морт и Рикти',      note: 'Кислотные вихри, гаражный хайтек, шкалы радиации' },
        { id: 'federation',group: 'screen',      status: 'planned', price: 8,
          name: 'Галактическая контора', note: 'Бюрократический штамп, противный звук доступа' },
        { id: 'shack',     group: 'screen',      status: 'planned', price: 8,
          name: 'Хижина чудес',      note: 'Пожелтевший дневник, диаграммы, тайные символы' },
        { id: 'triangle',  group: 'screen',      status: 'planned', price: 10,
          name: 'Треугольник',       note: 'Жёлто-чёрный хаос, экран трескается' },
        { id: 'questmode', group: 'screen',      status: 'planned', price: 6,
          name: 'Время похода',      note: 'Сказочная карта, стрелка-меч, звук лута' },
        { id: 'icekingdom',group: 'screen',      status: 'planned', price: 6,
          name: 'Ледяное королевство', note: 'Морозное свечение, метель, снежинки у солнца' },
        { id: 'express',   group: 'screen',      status: 'planned', price: 8,
          name: 'Служба доставки 3000', note: 'Потёртый пульт, мини-карта секторов' },
        { id: 'scavenger', group: 'screen',      status: 'planned', price: 8,
          name: 'Мусорщик',          note: 'Пыльный экран, SOLAR CHARGE, механический вздох' },
        { id: 'yellowcast',group: 'screen',      status: 'planned', price: 6,
          name: 'Жёлтый прогноз',    note: 'Чёрная обводка, солнце-смайлик, телевизионный джингл' },
        { id: 'watercolor',group: 'screen',      status: 'planned', price: 10,
          name: 'Акварель',          note: 'Тёплая живопись, фактура бумаги, музыка шкатулки' },
        { id: 'flyingisle',group: 'screen',      status: 'planned', price: 10,
          name: 'Летающий остров',   note: 'Небесные камни, шестерёнки, мистическое гудение' },
        { id: 'rubberhose',group: 'screen',      status: 'planned', price: 10,
          name: 'Резиновый шланг',   note: 'Покадровая анимация, брызги чернил, джаз и винил' },
        { id: 'satellite', group: 'screen',      status: 'planned', price: 6,
          name: 'Спутник',           note: 'Спутниковые текстуры, сетка координат, зум камеры' }
    ]
};
